version: '3'
services:
  app:
    tty: true
    image: 'node:8.11'
    ports:
      - "${EMAIL_CRACK_PORT-8472}:8472"
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    restart: on-failure
    entrypoint: node_modules/.bin/gulp
    environment:
      NODE_ENV: development
      PORT: 8472
volumes:
  node_modules: {}
